### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GITchristoph** [graham22/ModbusTool#1]
Dear Graham,

Thanks a lot for writing a Software and making it available here.

Before I try and explore its capabilities I wanted to ask one question.

I am looking for a piece of Software that can read as a Master via Modbus TCP data from 3 Slaves each with its own IP address and that then can give out the read data via Modbus Slave (or Master if Slave is not possible) on a single IP address.

The idea is to bundle the information from 3 IP adresses to just 1 IP address.

Can you tell me if your Software can do this? 
Or do you maybe know a Software that can do this? ( ;-) )

Your time of even reading this message is very much appreciated so thanks a lot again for your software and in advance also for your answer,

Chris

**Comment by graham22** [comment]
Hi Chris,
The app can only connect to one slave at a time, you would have to write
some custom software for this,
There are some good modbus libraries in nuget if you're using visual studio
c#

Graham

**Comment by GITchristoph** [comment]
Thanks so much for the answer, Graham. 

I will look and hipe to sort it out. 

Cheers, Chris
