### ISSUE TITLE
Slave ignores writes to addresses other than 0

### ISSUE THREAD

**Issue by DennisKuypers** [graham22/ModbusTool#7]
Writes are denied, slave says:

> Received address is not within viewable range, Received address: 1

See https://github.com/graham22/ModbusTool/blob/master/ModbusSlave/SlaveForm.cs#L340
Checks are always denied, because it's using https://github.com/graham22/ModbusTool/blob/master/CommonControls/BaseForm.cs#L20 which is always 0

**Comment by ThomasvLingen** [comment]
Can confirm this is a problem, I've reproduced it with the following steps (TCP mode):
* Performing a "Write Single Coil" call to address `0x0000` succeeds
* Performing a "Write Single Coil" call to address `0x0001` fails

Something I want to point out: The value is never written in the simulated slave, but this is in no way signaled back to the Modbus Client. The response sent back is just a normal response, which implies the write has succeeded.
